FROM registry.baidubce.com/device/paddle-npu:cann80RC1-ubuntu20-aarch64-gcc84-py310

WORKDIR /home

RUN git clone https://github.com/PaddlePaddle/PaddleCustomDevice 
RUN cd PaddleCustomDevice/backends/npu 
RUN pip3 install paddlepaddle -i https://www.paddlepaddle.org.cn/packages/nightly/cpu/ 
ENV WITH_TESTING=OFF 
RUN bash /home/PaddleCustomDevice/backends/npu/tools/compile.sh
RUN pip3 install /home/PaddleCustomDevice/backends/npu/build/dist/paddle_custom_npu-0.0.0-cp310-cp310-linux_aarch64.whl



