FROM swr.cn-south-1.myhuaweicloud.com/ascendhub/cann:8.1.rc1-910b-ubuntu22.04-py3.10

RUN apt update && apt install vim -y

RUN pip3 install torch==2.1.0  pyyaml setuptools torch-npu==2.1.0.post12

WORKDIR /home

COPY . .

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    python -m pip --no-cache-dir install jupyterlab && \
    rm -rf /root/.cache/pip /tmp/*

